apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mekn-backend-hpa
  namespace: ahmedhemida
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mekn-backend
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80