apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: ahmedhemida
spec:
  storageClassName: 'rook-cephfs'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi